import type { PolyDocument } from '../types'
import { detectFaces } from './faces'
import { facePointsToVecs, interiorPoint } from '../lib/geometry'

/** Format a number for .poly output: shortest round-trippable decimal, no negative zero. */
function fmt(v: number): string {
  if (Object.is(v, -0)) return '0'
  if (!Number.isFinite(v)) return '0'
  return String(v)
}

export interface SerializeOptions {
  /** Emit the leading comment header. Default true. */
  header?: boolean
}

export interface SerializeResult {
  text: string
  /** Number of detected faces with no entry in `faceTypes` (defaulted to mattype 0). */
  untypedFaceCount: number
}

/**
 * Serialize an editor document to a DES3D-compatible 2D `.poly` (PSLG) string.
 * Each detected face emits exactly one region line; untyped faces fall back to
 * mattype 0 (`untypedFaceCount` reports how many faces took the fallback).
 */
export function serializePoly(doc: PolyDocument, opts: SerializeOptions = {}): SerializeResult {
  const { points, lines, faceTypes } = doc
  const indexOf = new Map<string, number>()
  points.forEach((p, i) => indexOf.set(p.id, i))

  const validLines = lines.filter(
    (s) => indexOf.has(s.p0) && indexOf.has(s.p1) && s.p0 !== s.p1,
  )

  // Compute faces inline; each face yields one region line.
  const faces = detectFaces(points, lines)
  const pointById = new Map(points.map((p) => [p.id, p]))
  let untypedFaceCount = 0

  const out: string[] = []
  if (opts.header !== false) {
    out.push('# Generated by poly-forge')
  }

  // Node coordinates
  out.push('#### node coordinates ####')
  out.push('# npoints ndims 0 0')
  out.push(`${points.length} 2 0 0`)
  out.push('# i x z')
  points.forEach((p, i) => out.push(`${i} ${fmt(p.x)} ${fmt(p.z)}`))

  // Segments
  out.push('#### segments ####')
  out.push('# nsegments has_bdryflag')
  out.push(`${validLines.length} 1`)
  out.push('# j p0 p1 bdry_flag')
  validLines.forEach((s, j) => {
    out.push(`${j} ${indexOf.get(s.p0)} ${indexOf.get(s.p1)} ${s.bdryFlag}`)
  })

  // Holes (DES3D requires 0)
  out.push('#### holes ####')
  out.push('0')

  // Regions: one per detected face.
  out.push('#### regions ####')
  out.push('# nregions')
  out.push(`${faces.length}`)
  out.push('# k xk zk mattype size')
  faces.forEach((face, k) => {
    const verts = facePointsToVecs(face.pointIds, pointById)
    const seed = interiorPoint(verts)
    const spec = faceTypes[face.id]
    const mattype = spec?.mattype ?? 0
    const size = spec?.size ?? -1
    if (!spec) untypedFaceCount++
    out.push(`${k} ${fmt(seed.x)} ${fmt(seed.z)} ${mattype} ${fmt(size)}`)
  })

  return { text: out.join('\n') + '\n', untypedFaceCount }
}
