import type { PolyDocument } from '../types'

/** Format a number for .poly output: shortest round-trippable decimal, no negative zero. */
function fmt(v: number): string {
  if (Object.is(v, -0)) return '0'
  if (!Number.isFinite(v)) return '0'
  return String(v)
}

export interface SerializeOptions {
  /** Emit the leading comment header. Default true. */
  header?: boolean
}

/**
 * Serialize an editor document to a DES3D-compatible 2D `.poly` (PSLG) string.
 * Points are reindexed to contiguous 0-based integers; segment endpoints are remapped.
 */
export function serializePoly(doc: PolyDocument, opts: SerializeOptions = {}): string {
  const { points, segments, regions, domain } = doc
  const indexOf = new Map<string, number>()
  points.forEach((p, i) => indexOf.set(p.id, i))

  const validSegments = segments.filter(
    (s) => indexOf.has(s.p0) && indexOf.has(s.p1) && s.p0 !== s.p1,
  )

  const lines: string[] = []
  if (opts.header !== false) {
    lines.push('# Generated by poly-forge')
    lines.push(
      `# Domain x[${fmt(domain.xmin)}, ${fmt(domain.xmax)}] z[${fmt(domain.zmin)}, ${fmt(
        domain.zmax,
      )}] (m); meshing_option=${domain.meshingOption}`,
    )
  }

  // Node coordinates
  lines.push('#### node coordinates ####')
  lines.push('# npoints ndims 0 0')
  lines.push(`${points.length} 2 0 0`)
  lines.push('# i x z')
  points.forEach((p, i) => lines.push(`${i} ${fmt(p.x)} ${fmt(p.z)}`))

  // Segments
  lines.push('#### segments ####')
  lines.push('# nsegments has_bdryflag')
  lines.push(`${validSegments.length} 1`)
  lines.push('# j p0 p1 bdry_flag')
  validSegments.forEach((s, j) => {
    lines.push(`${j} ${indexOf.get(s.p0)} ${indexOf.get(s.p1)} ${s.bdryFlag}`)
  })

  // Holes (DES3D requires 0)
  lines.push('#### holes ####')
  lines.push('0')

  // Regions
  lines.push('#### regions ####')
  lines.push('# nregions')
  lines.push(`${regions.length}`)
  lines.push('# k xk zk mattype size')
  regions.forEach((r, k) => {
    lines.push(`${k} ${fmt(r.x)} ${fmt(r.z)} ${r.mattype} ${fmt(r.size)}`)
  })

  return lines.join('\n') + '\n'
}
